### ISSUE TITLE
StandBy Mode not starting and stopping correctly

### ISSUE THREAD

**Issue by rallen911** [ExTool/ExTool-EDMC-Plugin#1]
I run ED in windowed/borderless mode on my main monitor, and I have Discord, etc. open on the other one.  After starting EDMC and then ED, things seem to be working fine.  If I switch to Discord, I see the ExTool status go to StandBy Mode, as expected.  When I switch back to ED, it does not always leave StandBy Mode (most of the time actually).  When it fails to switch, it appears to be stuck, and I have to restart both EDMC and ED to get things going again.

I tried #extool toggle twice to turn it off and back on, but did not have any effect.

By the way, should be "deactivated" without the 's'. :)

I discovered that hitting F10 kickstarts it to working again.

I'm also having problems with the transponder deactivating for no apparent reason.

System Info:
- Intel i7 7700K
- 16 GB RAM
- GTX 1060 3GB
- Windows 10 Pro

**Comment by Sileo35** [comment]
Do you have the same problem in full screen mode ?
Can you activate the "debug mode" in settings and send the EDMarketConnector.log in %temp% directory when the error appears ?
You need at least wait 5 seconds when you go back on Elite Dangerous to resume the automatic screenshot.

Edit: I have made an update to 0.8.4.2. Can you try this new version and tell me if you have the same problem ?
http://elite.laulhere.com/ExTool/EDMC/latest_ExTool.zip
