### ISSUE TITLE
v1.0.0 is source code so I can't install it?

### ISSUE THREAD

**Issue by badbud65** [ExTool/ExTool-EDMC-Plugin#4]
The link from EDMC takes me to the new version v1.0..0 howvere that is just source code and I don't know what to do or hoa to install it. 

Have the right files been uploaded?
Have I misunderstood something?
How do I upgrade to v1.0.0?

**Comment by teamcba** [comment]
It's all in python so there's not in install file.
Download the source zip file.
open the EDMC plugins folder
if you have an existing Extools folder rename it with .disabled on the end e.g. ExTool-EDMC-Plugin-master.disabled
open the zip file and copy the "ExTool-EDMC-Plugin-1.0.0" folder to the plugins folder.
restart EDMC
